[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../1_types" }
rusqlite = { workspace = true }
async-sqlite = { workspace = true }
debug_print = { workspace = true }
thiserror.workspace = true
once_cell = { workspace = true }
asynciter = { workspace = true }

[dev-dependencies]
tiny-bip39.workspace = true
