cargo-features = ["profile-rustflags"]


[workspace]
members = [
  "1_types",
  "2_store",
  "3_handles",
  "4_font_and_icons",
  "iced_ui",
  "mercurium",
]
workspace.resolver = "2"

package.edition = "2021"


[profile.release]
panic = "unwind"
strip = "symbols"
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.dev]
opt-level = 0
lto = "off"

[workspace.dependencies]
scrypto = { version = "1.3.0" }
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
iced = { version = "0.13.1", features = [
  "tokio",
  "lazy",
  "advanced",
  "image",
  "qr_code",
] }
async-sqlite = { version = "0.3.1", features = [
  "bundled-sqlcipher-vendored-openssl",
] }
reqwest = { version = "*", features = ["blocking", "json"] }
openssl-sys = { version = "*", features = ["vendored"] }
flate2 = "*"
thiserror = "*"
bytes = "*"
image = "*"
fast_image_resize = "3.0.4"
tiny-bip39 = "*"
slip10_ed25519 = "*"
ed25519-dalek-fiat = "*"
rand = "*"
ring = "*"
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }
debug_print = "*"
regex = { version = "*" }
once_cell = "*"
lazy_static = { version = "*" }
const_format = "*"
radix-gateway-sdk = { git = "https://github.com/borderline-labs/radix-gateway-sdk.git" }
asynciter = "*"
futures = "*"


# Windows specific imports
winapi = { version = "*", features = ["winuser"] }
windows = { version = "*", features = [
  "Win32_System",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Cryptography",
  "Win32_Security_Credentials",
] }
# Experimantal
slint = { version = "1.8.0" }
