cargo-features = ["profile-rustflags"]


[workspace]
members = [
    "01_ports_and_adapters/app_path",
    "01_ports_and_adapters/data_stores",
    "01_ports_and_adapters/icon_provider",
    "01_ports_and_adapters/ledger_connector",
    "01_ports_and_adapters/secrets_store",
    "0_deps",
    "1_types",
    "4_font_and_icons",
    "5_wallet",
    "iced_ui",
    "mercurium",
]

workspace.resolver = "3"
package.version = "0.0.1"
package.edition = "2024"


[profile.release]
panic = "unwind"
strip = "symbols"
opt-level = 3
lto = "fat"
codegen-units = 1


[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"


[workspace.dependencies]
deps = { path = "0_deps" }

serde = { version = "*", features = ["derive"] }
zeroize = { version = "*", features = ["zeroize_derive"] }
hot-lib-reloader = { version = "0.7.0" }
thiserror = "2.0"

#used from the deps crate
iced = { version = "0.14.0", default-features = false, features = [
    "wgpu",
    "tokio",
    "image",
    "qr_code",
    "advanced",
    "debug",
    "wayland",
] }
hot_ice = { git = "https://github.com/aleanon/hot_ice.git", branch = "main", features = ["tokio"] }
scrypto = { version = "1.3.0" }
radix-transactions = { version = "1.3.1" }
radix-common = { version = "1.3.1" }
radix-engine-interface = { version = "1.3.1" }
tokio = { version = "1.50", features = ["full"] }
serde_json = { version = "1.0" }
async-sqlite = { version = "0.5.0", features = [
    "bundled-sqlcipher-vendored-openssl",
] }
reqwest = { version = "0.13", features = ["blocking", "json"] }
openssl-sys = { version = "0.9", features = ["vendored"] }
flate2 = "1.1"
bytes = "1.11"
image = "0.25"
fast_image_resize = { version = "5.1.3", features = ["image"] }
tiny-bip39 = "*"
slip10_ed25519 = "*"
ed25519-dalek-fiat = "*"
rand = "*"
ring = "*"
debug_print = "*"
regex = { version = "*" }
once_cell = "*"
lazy_static = { version = "*" }
const_format = "*"
radix-gateway-sdk = { git = "https://github.com/aleanon/radix-gateway-sdk-fork.git" }
asynciter = "*"
futures = "*"
bincode = "2.0.1"
no-mangle-if-debug = "0.1"
simple_logger = "*"
async-trait = "*"
encrypt = { version = "0.1.0", git = "https://github.com/aleanon/encrypt.git", branch = "main" }

# Windows specific imports
winapi = { version = "*", features = ["winuser"] }
windows = { version = "*", features = [
    "Win32_System",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Security_Credentials",
] }
