cargo-features = ["profile-rustflags"]

[package]
name = "mercurium"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
reload = ["dep:hot-lib-reloader"]

[profile.reload]
inherits = "dev"
rustflags = ["-C", "prefer-dynamic", "-Zmacro-backtrace"]
opt-level = 3
lto = false
codegen-units = 1
debug-assertions = true
debug = 1
features = ["reload"]

[profile.reload.package."*"]
opt-level = 3
codegen-units = 1

[dependencies]
iced_ui = { path = "../iced_ui" }
styles = { path = "../iced_ui/styles" }
tokio = { workspace = true }
hot-lib-reloader = { version = "0.7.0", optional = true }
