cargo-features = ["profile-rustflags"]

[package]
name = "font_and_icons"
version = "0.1.0"
edition.workspace = true


[lib]
crate-type = ["rlib", "cdylib"]

[profile.dev]
rustflags = ["-C", "prefer-dynamic"]


[dependencies]
deps = { path = "../0_deps" }


