
[package]
name = "iced_ui"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
#crate-type = ["dylib"]

[features]
default = []
noupdate = []

[dependencies]
types = { path = "../1_types" }
store = { path = "../2_store" }
handles = { path = "../3_handles" }
font_and_icons = { path = "../4_font_and_icons" }
wallet = { path = "../5_wallet" }
ravault_iced_theme = { path = "./theme" }
ravault_widgets = { path = "./widgets" }
iced = { workspace = true }
# iced_aw = { workspace = true, features = ["icons"] }
zeroize = { workspace = true }
thiserror = { workspace = true }
tiny-bip39 = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
scrypto = { workspace = true }
lazy_static = { workspace = true }

debug_print.workspace = true
# hot-lib-reloader = { workspace = true, optional = true }

[dev-dependencies]
