[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]


[build.dev]
codegen-backend = "cranelift"
# rustflags = ["-Z", "threads=8"]

[profile.dev]
opt-level = 0
lto = false
codegen-units = 1
debug-assertions = true
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[build.reload]
codegen-backend = "cranelift"

[profile.reload]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "prefer-dynamic",
    "-C",
    "link-args=-Wl,--whole-archive",
    "-C",
    "link-args=-Wl,--no-as-needed",
]
inherits = "dev"
opt-level = 0
lto = false
codegen-units = 1
debug-assertions = true
debug = false
features = ["reload"]

[profile.reload.package."*"]
opt-level = 3
codegen-units = 1

[profile.hot-ice-bin]
inherits = "dev"
opt-level = 0
lto = false
codegen-units = 1
debug-assertions = true
debug = true
features = ["reload"]

[profile.hot-ice-bin.package."*"]
opt-level = 3
codegen-units = 1
