[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"


[build.dev]
# rustflags = ["-Z", "threads=8"]
codegen-backend = "cranelift"

[profile.dev]
opt-level = 0
lto = false
codegen-units = 1
debug-assertions = true
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[profile.reload]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=-Wl,--whole-archive",
]
inherits = "dev"
opt-level = 0
lto = false
codegen-units = 1
debug-assertions = true
debug = true
features = ["reload"]

[profile.reload.package."*"]
opt-level = 3
codegen-units = 1
