[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
# crate-type = ["rlib", "cdylib"]


[build.dev]
# rustflags = ["-Z", "threads=8"]

[build.reload]
# rustflags = ["-Z", "threads=8", "-C", "prefer-dynamic", "--crate-type cdylib"]
